--liquibase formatted sql

--changeset derkachev:0
CREATE TABLE users
(
    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    phone     VARCHAR(20),
    bot_state VARCHAR(20)
);
CREATE TABLE cat
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    cat_name             VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);

--changeset couldlie:0.1
CREATE TABLE dog
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    dog_name            VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);

--changeset couldlie:0.2
ALTER TABLE users RENAME TO user_dog;
CREATE TABLE user_cat
(
    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL,
    phone     VARCHAR(20),
    bot_state VARCHAR(20)
);

--changeset couldlie:0.3
CREATE TABLE shelter
(
    number    BIGINT generated by default as identity primary key,
    name      VARCHAR(20),
    address   VARCHAR(50),
    telephone_number    VARCHAR(20),
    work_schedule       VARCHAR(20),
    shelter_type        VARCHAR(20)
);

--changeset couldlie:0.4
CREATE TABLE user_table
(

    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    name      VARCHAR(20)

);

--changeset couldlie:0.5
DROP TABLE shelter;
ALTER TABLE user_cat DROP COLUMN bot_state;
ALTER TABLE user_dog DROP COLUMN bot_state;

--changeset couldlie:0.6
AlTER TABLE user_table ADD COLUMN user_cat_id BIGINT;
AlTER TABLE user_table ADD COLUMN user_dog_id BIGINT;

--changeset couldlie:0.7
ALTER TABLE user_cat ADD COLUMN cat_id BIGINT UNIQUE;
ALTER TABLE user_dog ADD COLUMN dog_id BIGINT UNIQUE;

--changeset couldlie:0.8
CREATE TABLE user_feedback
(

    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    phone_number   VARCHAR(20) NOT NULL UNIQUE,
    name      VARCHAR(20),
    feedback BOOLEAN

);

--changeset couldlie:0.9
CREATE TABLE super_user
(
    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    name      VARCHAR(20)
);

--changeset couldlie:0.91
ALTER TABLE cat ADD COLUMN user_cat_id BIGINT;
ALTER TABLE dog ADD COLUMN user_dog_id BIGINT;

--changeset couldlie:1.0
CREATE TABLE report_cat
(
    id        BIGINT generated by default as identity primary key,
    user_cat    BIGINT NOT NULL UNIQUE,
    report VARCHAR(100) UNIQUE ,
    report_date DATE NOT NULL UNIQUE,
    photo_id VARCHAR(100) UNIQUE,
    report_accepted BOOLEAN UNIQUE
);
CREATE TABLE report_dog
(
    id        BIGINT generated by default as identity primary key,
    user_dog    BIGINT NOT NULL UNIQUE,
    report VARCHAR(100) UNIQUE ,
    report_date DATE NOT NULL UNIQUE,
    photo_id VARCHAR(100) UNIQUE,
    report_accepted BOOLEAN UNIQUE
);
CREATE SEQUENCE report_cat_seq
    MINVALUE 1
    MAXVALUE 50
    INCREMENT BY 1
    CACHE 20;
CREATE SEQUENCE report_dog_seq
    MINVALUE 1
    MAXVALUE 50
    INCREMENT BY 1
    CACHE 20;

--changeset couldlie:1.2
ALTER TABLE user_cat ADD COLUMN trial_period INT;
ALTER TABLE user_dog ADD COLUMN trial_period INT;

--changeset couldlie:1.3
ALTER TABLE user_cat ADD COLUMN user_id BIGINT;
ALTER TABLE user_dog ADD COLUMN user_id BIGINT;

--changeset couldlie:1.4
ALTER TABLE user_cat ADD COLUMN user_cat_id BIGINT;
ALTER TABLE user_dog ADD COLUMN user_dog_id BIGINT;

--changeset couldlie:1.5
ALTER TABLE user_cat ADD COLUMN user_need_help BOOLEAN;
ALTER TABLE user_dog ADD COLUMN user_need_help BOOLEAN;
ALTER TABLE user_feedback ADD COLUMN shelter_type VARCHAR(20);