--liquibase formatted sql

--changeset derkachev:0
CREATE TABLE users
(
    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    phone     INT,
    bot_state VARCHAR(20)
);
CREATE TABLE cat
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    cat_name             VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);

--changeset couldlie:0.1
CREATE TABLE dog
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    dog_name            VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);

--changeset couldlie:0.2
ALTER TABLE users RENAME TO user_dog;
CREATE TABLE user_cat
(
    id        BIGINT generated by default as identity primary key,
    chat_id   BIGINT NOT NULL UNIQUE,
    phone     INT,
    bot_state VARCHAR(20)
);